import { writeFileSync } from "node:fs";
import { RULES } from "../src/rules";
import { SEVERITY_ORDER } from "../src/engine/severity";

/**
 * Generates RULES.md from rule metadata so documentation cannot drift
 * from what the scanner actually enforces.
 */
const sorted = [...RULES].sort(
  (a, b) =>
    SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity) ||
    a.id.localeCompare(b.id),
);

const header = `# Rule catalog

<!-- Auto-generated by \`pnpm rules:doc\` — do not edit by hand. -->

${sorted.length} rules ship with this version. Every finding links to remediation guidance; severity drives the \`--fail-on\` gate.

| rule id | severity | category | detects |
| --- | --- | --- | --- |
`;

const rows = sorted
  .map(
    (rule) => `| \`${rule.id}\` | **${rule.severity}** | ${rule.category} | ${rule.description} |`,
  )
  .join("\n");

writeFileSync(new URL("../RULES.md", import.meta.url), header + rows + "\n");
console.log(`RULES.md generated (${sorted.length} rules)`);
